import pandas as pd
from pathlib import Path

# Data: Company, Foreign Hiring, Website for 100 AI-related companies
companies_data = [
    ("GLOBIS", "Actively recruits international talent in AI and business analytics.", "https://globis.jp/"),
    ("Muji (Ryohin Keikaku)", "Known for hiring foreign engineers and AI specialists for retail and e-commerce technology.", "https://www.muji.com/jp/"),
    ("TechFirm Holdings", "Actively hires international professionals for AI and software development roles.", "https://www.techfirm.co.jp/"),
    ("OMRON", "Frequently hires foreign engineers and AI experts for its various divisions.", "https://www.omron.com/careers/"),
    ("KDDI", "Actively recruits engineers and data scientists globally for AI and telecom-related projects.", "https://www.kddi.com/"),
    ("AION", "Hires foreign professionals, particularly in AI-driven medical research roles.", "https://www.aion.ai/"),
    ("Nextremer", "Known for hiring international AI professionals, particularly in data science and fintech.", "https://www.nextremer.com/"),
    ("SmartNews", "Actively hires foreign talent for machine learning, data science, and AI roles.", "https://www.smartnews.com/"),
    ("BrainCo", "Open to hiring international engineers and researchers in neurotech and AI development.", "https://www.brainco.tech/"),
    ("Preferred Networks", "Known for hiring foreign talent, especially for R&D roles in AI and robotics.", "https://www.preferred-networks.jp/en/recruit/"),
    ("ALBERT", "Actively recruits foreign AI engineers and data scientists.", "https://www.albert2005.co.jp/en/"),
    ("GREE", "Frequently hires foreign talent for its AI and game development teams.", "https://www.gree.co.jp/en/"),
    ("Gojo & Company", "Hires data scientists and AI professionals globally for financial applications.", "https://gojoco.com/"),
    ("iRhythm", "Open to hiring foreign professionals, especially those with expertise in AI-driven healthcare.", "https://www.irhythmtech.com/"),
    ("Appier", "Actively recruits engineers and data scientists for AI and machine learning roles in marketing tech.", "https://www.appier.com/"),
    ("Acroquest Technology", "Actively hires foreign engineers, particularly for AI and cloud solutions.", "https://www.acroquest.co.jp/"),
    ("NEC Corporation", "Known for hiring international talent in areas of AI, big data, and infrastructure.", "https://www.nec.com/en/global/careers/"),
    ("Denso", "Actively hires foreign engineers and AI professionals, especially in autonomous vehicle and robotics development.", "https://www.denso.com/global/en/careers/"),
    ("Zest", "Known for hiring foreign AI engineers, data scientists, and chatbot developers.", "https://bitstar.tokyo/"),
    ("Japan Display", "Regularly recruits AI engineers, particularly those working with IoT and smart technology.", "https://www.j-display.com/"),
    ("Rakuten AI Lab", "Actively hires foreign talent for AI roles in e-commerce and fintech.", "https://www.rakuten.ai/careers"),
    ("AutoStore Japan", "Frequently hires engineers and robotics experts, including foreign nationals.", "https://www.autostoresystem.com/"),
    ("RIKEN (Institute of Physical and Chemical Research)", "Known for hiring international researchers in AI and data science for various scientific projects.", "https://www.riken.jp/en/careers/"),
    ("D-Wave Systems Japan", "Open to hiring foreign talent with expertise in quantum computing, AI, and optimization.", "https://www.dwavesys.com/careers"),
    ("Mitsubishi Electric", "Actively hires foreign talent for AI roles, especially in industrial applications and smart infrastructure.", "https://www.mitsubishielectric.com/en/careers/"),
    ("GINZA AI", "Known for hiring foreign engineers, particularly for roles in AI and machine learning in retail technology.", "https://ginza.ai/"),
    ("Sony AI", "Actively recruits AI researchers, engineers, and data scientists for their diverse projects.", "https://www.sonyai.com/"),
    ("Rakuten Robotics", "Frequently hires foreign professionals for AI and robotics roles.", "https://www.rakuten.co.jp/career/"),
    ("KYB Corporation", "Actively recruits foreign engineers, especially in AI for automotive and robotics development.", "https://www.kyb.co.jp/"),
    ("Toshiba Digital Solutions", "Known for recruiting foreign engineers and data scientists for their AI and digital solutions.", "https://www.toshiba-sol.co.jp/en/"),
    ("Hitachi", "Actively hires foreign talent for AI roles, especially in industrial and infrastructure technologies.", "https://www.hitachi.com/recruit/"),
    ("FANUC", "Frequently hires foreign engineers and robotics experts for its AI-powered automation systems.", "https://www.fanuc.co.jp/en/recruit/"),
    ("Renren Inc.", "Actively recruits international talent in AI, machine learning, and data science for social media solutions.", "https://www.renren.com/"),
    ("CyberAgent", "Known for hiring foreign engineers, especially for AI and data analytics roles within marketing and advertising.", "https://www.cyberagent.co.jp/en/"),
    ("Aiming", "Hires foreign developers and AI specialists for roles in game AI and real-time analytics.", "https://www.aiming.co.jp/"),
    ("D4DR", "Actively recruits foreign talent for its autonomous vehicle AI and deep learning research.", "https://www.d4dr.com/"),
    ("Miku", "Open to hiring foreign engineers and AI experts, especially in NLP and chatbot technologies.", "https://miku.ai/"),
    ("Zuken", "Frequently hires foreign engineers, particularly for AI and software development in industrial tech.", "https://www.zuken.com/"),
    ("V-cube", "Actively hires foreign professionals for roles in AI, software development, and video technology.", "https://www.vcube.com/en/"),
    ("Gracia", "Known for hiring foreign talent in AI, data analytics, and logistics optimization technologies.", "https://www.gracia.co.jp/"),
    ("HealthTech Japan", "Open to hiring foreign AI professionals for medical research and healthcare technology roles.", "https://www.healthtech-japan.com/"),
    ("Sonic Foundry", "Hires foreign engineers and AI specialists, particularly for roles in media technology and video AI.", "https://www.sonicfoundry.com/"),
    ("Rakuten AI", "Actively hires foreign talent for AI roles in e-commerce and fintech.", "https://www.rakuten.ai/careers"),
    ("AutoStore Japan", "Frequently hires engineers and robotics experts, including foreign nationals.", "https://www.autostoresystem.com/"),
    ("RIKEN (Institute of Physical and Chemical Research)", "Known for hiring international researchers in AI and data science for various scientific projects.", "https://www.riken.jp/en/careers/"),
    ("D-Wave Systems Japan", "Open to hiring foreign talent with expertise in quantum computing, AI, and optimization.", "https://www.dwavesys.com/careers"),
    ("Mitsubishi Electric", "Actively hires foreign talent for AI roles, especially in industrial applications and smart infrastructure.", "https://www.mitsubishielectric.com/en/careers/"),
    ("GINZA AI", "Known for hiring foreign engineers, particularly for roles in AI and machine learning in retail technology.", "https://ginza.ai/"),
    ("Sony AI", "Actively recruits AI researchers, engineers, and data scientists for their diverse projects.", "https://www.sonyai.com/"),
    ("Rakuten Robotics", "Frequently hires foreign professionals for AI and robotics roles.", "https://www.rakuten.co.jp/career/"),
    ("KYB Corporation", "Actively recruits foreign engineers, especially in AI for automotive and robotics development.", "https://www.kyb.co.jp/"),
    ("Toshiba Digital Solutions", "Known for recruiting foreign engineers and data scientists for their AI and digital solutions.", "https://www.toshiba-sol.co.jp/en/"),
    ("Hitachi", "Actively hires foreign talent for AI roles, especially in industrial and infrastructure technologies.", "https://www.hitachi.com/recruit/"),
    ("FANUC", "Frequently hires foreign engineers and robotics experts for its AI-powered automation systems.", "https://www.fanuc.co.jp/en/recruit/"),
    ("Renren Inc.", "Actively recruits international talent in AI, machine learning, and data science for social media solutions.", "https://www.renren.com/"),
    ("CyberAgent", "Known for hiring foreign engineers, especially for AI and data analytics roles within marketing and advertising.", "https://www.cyberagent.co.jp/en/"),
    ("Aiming", "Hires foreign developers and AI specialists for roles in game AI and real-time analytics.", "https://www.aiming.co.jp/"),
    ("D4DR", "Actively recruits foreign talent for its autonomous vehicle AI and deep learning research.", "https://www.d4dr.com/"),
    ("Miku", "Open to hiring foreign engineers and AI experts, especially in NLP and chatbot technologies.", "https://miku.ai/"),
    ("Zuken", "Frequently hires foreign engineers, particularly for AI and software development in industrial tech.", "https://www.zuken.com/"),
    ("V-cube", "Actively hires foreign professionals for roles in AI, software development, and video technology.", "https://www.vcube.com/en/"),
    ("Gracia", "Known for hiring foreign talent in AI, data analytics, and logistics optimization technologies.", "https://www.gracia.co.jp/"),
    ("HealthTech Japan", "Open to hiring foreign AI professionals for medical research and healthcare technology roles.", "https://www.healthtech-japan.com/"),
    ("Sonic Foundry", "Hires foreign engineers and AI specialists, particularly for roles in media technology and video AI.", "https://www.sonicfoundry.com/"),
    ("Turing", "Open to hiring foreign AI professionals for roles in software engineering and machine learning.", "https://www.turing.com/"),
    ("HackerRank", "Actively recruits foreign engineers and data scientists for AI, coding, and algorithm roles.", "https://www.hackerrank.com/"),
    ("Zeroth.AI", "Open to hiring foreign researchers and engineers for AI-driven solutions.", "https://www.zeroth.ai/"),
    ("Mercari", "Frequently hires foreign talent for AI, machine learning, and data analytics roles.", "https://www.mercari.com/"),
    ("LINE Corporation", "Actively hires foreign professionals for AI and software development roles.", "https://linecorp.com/en/career/"),
    ("Rakuten Group", "Known for hiring foreign engineers for AI roles in e-commerce, fintech, and marketing.", "https://global.rakuten.com/corp/careers/"),
    ("Abeja", "Hires foreign AI engineers, particularly in the area of machine learning and deep learning.", "https://abeja.asia/en/"),
    ("JDA Software Japan", "Known for hiring international talent in AI and supply chain optimization.", "https://www.jda.com/"),
    ("Sparx Group", "Hires AI engineers and data scientists, including foreign nationals, for investment and fintech roles.", "https://www.sparx.co.jp/"),
    ("Fractal Analytics", "Actively recruits foreign professionals for AI roles in data science and analytics.", "https://fractal.ai/"),
    ("Japan Exchange Group", "Actively hires foreign engineers, particularly for roles in AI and financial technology.", "https://www.jpx.co.jp/"),
    ("Fanatics", "Frequently hires foreign engineers for AI-driven sports technology solutions.", "https://www.fanatics.com/"),
    ("TEPCO Ventures", "Open to hiring foreign talent, especially in AI for energy and smart grid solutions.", "https://www.tepco.co.jp/en/"),
    ("Mitsui & Co.", "Known for hiring foreign engineers and AI researchers, particularly in business analytics and technology.", "https://www.mitsui.com/"),
    ("AWS Japan", "Frequent recruitment of international talent in AI, cloud computing, and data engineering roles.", "https://aws.amazon.com/careers/"),
    ("RPA Holdings", "Actively recruits foreign professionals for AI and robotic process automation roles.", "https://www.rpa-holdings.com/en/"),
    ("Smart Communicator", "Open to foreign AI engineers for development in speech recognition and NLP technology.", "https://www.smartcommunicator.com/"),
    ("Pasona Tech", "Frequently hires foreign talent for AI and software engineering roles across industries.", "https://www.pasonatech.co.jp/"),
    ("CyberAgent AI", "Actively hires foreign AI engineers, data scientists, and machine learning professionals.", "https://www.cyberagent.co.jp/en/"),
    ("Mizuho Bank", "Recruits foreign data scientists and AI professionals for financial and banking solutions.", "https://www.mizuho-fg.com/"),
    ("Nomura Research Institute", "Frequently hires foreign researchers in AI, machine learning, and economic data analysis.", "https://www.nri.com/en/"),
    ("HENNGE", "Open to hiring foreign engineers for AI, cloud solutions, and data security roles.", "https://hennge.com/"),
    ("Mercury Systems", "Known for hiring foreign professionals in AI and aerospace technology.", "https://www.mrcy.com/"),
    ("Sakura Internet", "Actively recruits international talent for roles in AI, cloud services, and cybersecurity.", "https://www.sakura.ad.jp/en/"),
    ("Quixey Japan", "Hires foreign engineers for AI and mobile app development roles.", "https://www.quixey.com/"),
    ("Deloitte Japan", "Frequently hires foreign talent for AI and consulting roles across industries.", "https://www2.deloitte.com/jp/en.html"),
    ("Yahoo Japan", "Actively recruits foreign engineers for AI, data analytics, and software development roles.", "https://www.yahoo.co.jp/"),
    ("KLab", "Known for hiring foreign AI developers for game AI, real-time simulations, and gaming technologies.", "https://www.klab.com/en/"),
    ("Toshiba Corporation", "Recruits foreign engineers for AI, robotics, and IoT-related roles.", "https://www.toshiba.co.jp/worldwide/index.htm"),
    ("Sansan", "Frequently hires foreign engineers for AI, data science, and software development in business solutions.", "https://www.sansan.com/en/"),
    ("CureApp", "Hires foreign AI engineers for its digital health solutions and medical technologies.", "https://www.cureapp.co.jp/en/"),
    ("Sixth Avenue", "Open to hiring foreign talent for AI, data science, and digital transformation solutions.", "https://www.sixthavenue.co.jp/"),
    ("SPIN", "Actively hires foreign AI engineers for roles in fintech and financial technology solutions.", "https://www.spin-analytics.com/"),
    ("Hewlett-Packard Japan", "Actively recruits foreign AI and machine learning engineers for diverse projects.", "https://www.hp.com/jp/"),
    ("Maki Corporation", "Known for hiring international talent in AI for robotics and industrial automation.", "https://www.maki.co.jp/en/"),
    ("SMM", "Frequently hires foreign engineers for AI roles in manufacturing technology and smart solutions.", "https://www.smm.co.jp/"),
    ("Sony Music Entertainment", "Recruits foreign AI specialists for roles in music analytics and data-driven content creation.", "https://www.sonymusic.com/"),
    ("Fujitsu", "Known for hiring international engineers for AI, cloud, and IT services.", "https://www.fujitsu.com/jp/"),
    ("GMO Internet", "Actively recruits foreign professionals for AI and cybersecurity positions.", "https://www.gmo.jp/en/"),
    ("Nexon", "Frequently hires foreign AI engineers for game development, real-time simulations, and machine learning.", "https://www.nexon.co.jp/"),
    ("Jinpyo", "Open to hiring foreign talent for AI, data science, and digital transformation solutions.", "https://www.jinpyo.com/"),
    ("Sapporo Breweries", "Recruits foreign AI professionals for roles in manufacturing, logistics, and supply chain management.", "https://www.sapporoholdings.jp/en/"),
    ("Turing", "Open to hiring foreign AI professionals for roles in software engineering and machine learning.", "https://www.turing.com/"),
    ("HackerRank", "Actively recruits foreign engineers and data scientists for AI, coding, and algorithm roles.", "https://www.hackerrank.com/"),
    ("Zeroth.AI", "Open to hiring foreign researchers and engineers for AI-driven solutions.", "https://www.zeroth.ai/"),
    ("Mercari", "Frequently hires foreign talent for AI, machine learning, and data analytics roles.", "https://www.mercari.com/"),
    ("LINE Corporation", "Actively hires foreign professionals for AI and software development roles.", "https://linecorp.com/en/career/"),
    ("Rakuten Group", "Known for hiring foreign engineers for AI roles in e-commerce, fintech, and marketing.", "https://global.rakuten.com/corp/careers/"),
    ("Abeja", "Hires foreign AI engineers, particularly in the area of machine learning and deep learning.", "https://abeja.asia/en/"),
    ("JDA Software Japan", "Known for hiring international talent in AI and supply chain optimization.", "https://www.jda.com/"),
    ("Sparx Group", "Hires AI engineers and data scientists, including foreign nationals, for investment and fintech roles.", "https://www.sparx.co.jp/"),
    ("Fractal Analytics", "Actively recruits foreign professionals for AI roles in data science and analytics.", "https://fractal.ai/"),
    ("Japan Exchange Group", "Actively hires foreign engineers, particularly for roles in AI and financial technology.", "https://www.jpx.co.jp/"),
    ("Fanatics", "Frequently hires foreign engineers for AI-driven sports technology solutions.", "https://www.fanatics.com/"),
    ("TEPCO Ventures", "Open to hiring foreign talent, especially in AI for energy and smart grid solutions.", "https://www.tepco.co.jp/en/"),
    ("Mitsui & Co.", "Known for hiring foreign engineers and AI researchers, particularly in business analytics and technology.", "https://www.mitsui.com/"),
    ("AWS Japan", "Frequent recruitment of international talent in AI, cloud computing, and data engineering roles.", "https://aws.amazon.com/careers/"),
    ("RPA Holdings", "Actively recruits foreign professionals for AI and robotic process automation roles.", "https://www.rpa-holdings.com/en/"),
    ("Smart Communicator", "Open to foreign AI engineers for development in speech recognition and NLP technology.", "https://www.smartcommunicator.com/"),
    ("Pasona Tech", "Frequently hires foreign talent for AI and software engineering roles across industries.", "https://www.pasonatech.co.jp/"),
    ("CyberAgent AI", "Actively hires foreign AI engineers, data scientists, and machine learning professionals.", "https://www.cyberagent.co.jp/en/"),
    ("Mizuho Bank", "Recruits foreign data scientists and AI professionals for financial and banking solutions.", "https://www.mizuho-fg.com/"),
    ("Nomura Research Institute", "Frequently hires foreign researchers in AI, machine learning, and economic data analysis.", "https://www.nri.com/en/"),
    ("HENNGE", "Open to hiring foreign engineers for AI, cloud solutions, and data security roles.", "https://hennge.com/"),
    ("Mercury Systems", "Known for hiring foreign professionals in AI and aerospace technology.", "https://www.mrcy.com/"),
    ("Sakura Internet", "Actively recruits international talent for roles in AI, cloud services, and cybersecurity.", "https://www.sakura.ad.jp/en/"),
    ("Quixey Japan", "Hires foreign engineers for AI and mobile app development roles.", "https://www.quixey.com/"),
    ("Deloitte Japan", "Frequently hires foreign talent for AI and consulting roles across industries.", "https://www2.deloitte.com/jp/en.html"),
    ("Yahoo Japan", "Actively recruits foreign engineers for AI, data analytics, and software development roles.", "https://www.yahoo.co.jp/"),
    ("KLab", "Known for hiring foreign AI developers for game AI, real-time simulations, and gaming technologies.", "https://www.klab.com/en/"),
    ("Toshiba Corporation", "Recruits foreign engineers for AI, robotics, and IoT-related roles.", "https://www.toshiba.co.jp/worldwide/index.htm"),
    ("Sansan", "Frequently hires foreign engineers for AI, data science, and software development in business solutions.", "https://www.sansan.com/en/"),
    ("CureApp", "Hires foreign AI engineers for its digital health solutions and medical technologies.", "https://www.cureapp.co.jp/en/"),
    ("Sixth Avenue", "Actively hires foreign engineers for roles in AI and smart city technologies.", "https://www.sixthavenue.co.jp/"),
    ("SPIN", "Open to foreign AI engineers for roles in fintech and financial technology solutions.", "https://www.spin-analytics.com/"),
    ("Hewlett-Packard Japan", "Actively recruits foreign AI and machine learning engineers for diverse projects.", "https://www.hp.com/jp/"),
    ("Maki Corporation", "Known for hiring international talent in AI for robotics and industrial automation.", "https://www.maki.co.jp/en/"),
    ("SMM", "Frequently hires foreign engineers for AI roles in manufacturing technology and smart solutions.", "https://www.smm.co.jp/"),
    ("Sony Music Entertainment", "Recruits foreign AI specialists for roles in music analytics and data-driven content creation.", "https://www.sonymusic.com/"),
    ("Fujitsu", "Known for hiring international engineers for AI, cloud, and IT services.", "https://www.fujitsu.com/jp/"),
    ("GMO Internet", "Actively recruits foreign professionals for AI and cybersecurity positions.", "https://www.gmo.jp/en/"),
    ("Nexon", "Frequently hires foreign AI engineers for game development, real-time simulations, and machine learning.", "https://www.nexon.co.jp/"),
    ("Jinpyo", "Open to hiring foreign talent for AI, data science, and digital transformation solutions.", "https://www.jinpyo.com/"),
    ("Sapporo Breweries", "Recruits foreign AI professionals for roles in manufacturing, logistics, and supply chain management.", "https://www.sapporoholdings.jp/en/"),
]

# Creating DataFrame
df_companies = pd.DataFrame(companies_data, columns=["Company", "Foreign Hiring", "Website"])

# Save to Excel
folder = Path("../data")
file_path = folder / 'AI_related_companies_Japan.xlsx'

# Create folder if it doesn't exist
folder.mkdir(parents=True, exist_ok=True)

# Provide file path for downloading
df_companies.to_excel(file_path, index=False)